### ISSUE TITLE
server.cfg

### ISSUE THREAD

**Issue by Krenair** [Azelphur-Servers/TF2#12]
Another important file we should deal with in this repository is our equivalent of tf2/tf/cfg/server.cfg
I know that we currently use tf/cfg/surf/server.cfg etc.
We should `exec sensitiveinfo.cfg` or something to include sensitive data like rcon_password or tf_server_identity_token. Dunno about tf_server_identity_account_id.

**Comment by RobAWarner** [comment]
~~Another issue I noticed with the server cfg is that it gets added to 'cfg/sourcemod' instead of just 'cfg/'.~~

(Caused by incorrect config in surf.yaml, now fixed)

**Comment by Azelphur** [comment]
Fixed in e274d6a ... why did we need an issue for this xD

**Comment by Krenair** [comment]
I think I just turned all entries in our list into issues.
