### ISSUE TITLE
Spray report URL missing

### ISSUE THREAD

**Issue by Krenair** [Azelphur-Servers/TF2#13]
Reports used to come in like this: " for Bad spray: http://spray.tf2.azelphur.com/?page=spray&spray={SPRAY}&id=STEAM_0:0:1234567"
https://github.com/Azelphur/SourceIRC/blob/5bbd76bd34583a161ac059171301e46e3e353a02/scripting/SourceIRC/sourceirc-ticket.sp#L181
And it's blank for us, which is why it doesn't even try anymore: https://github.com/Azelphur-Servers/TF2/blob/master/sourcemod_configs/sourceirc_surf.cfg#L58
I wonder what is supposed to be done about the steamid though, there's no equivalent to {SPRAY} to substitute that in?

**Comment by RobAWarner** [comment]
I had a custom sourceirc-ticket.sp module that uses my spraymanager plugin. I will dig this back out and ensure it works.

**Comment by Krenair** [comment]
I have a custom sourceirc-ticket module that uses SourcePunish for the purposes of blocking specific users from reporting. I wonder if that's the problem.

**Comment by RobAWarner** [comment]
Fixed in 8441e42601fbae35b954aec270b6f9ea466c3e62
