### ISSUE TITLE
Fortwars mod no longer maintained? 

### ISSUE THREAD

**Issue by RobAWarner** [Azelphur-Servers/TF2#21]
So, I was looking at adding the fortwars server to this, and went to look for the latest version of the Fortwars mod only to find it has not been updated since the end of 2012!
However, I cannot seem to see another other mods like it.

So, do we continue to use the current mod? Does anyone know of a similar mod or want to see if it can be updated? I am currently not aware of any issue with it, although I personally have not played on it for a long time.

**Comment by Azelphur** [comment]
Yup, it's not broken.
