### ISSUE TITLE
Deploy BanDodgeBlocker?

### ISSUE THREAD

**Issue by Krenair** [Azelphur-Servers/TF2#3]
https://github.com/Zebetus/BanDodgeBlocker/blob/master/BanDodgeBlocker.sp

Maybe it should be integrated into SourcePunish as an optional thing...

**Comment by RobAWarner** [comment]
Full IP support should be added to SourcePunish so as that all punishment modules can utilise :)

**Comment by Azelphur** [comment]
I'd agree, integrate it into SourcePunish, it's good stuff. Make it a configurable feature or something.

**Comment by Azelphur** [comment]
I'm going to close this and re-open it on SourcePunish, as it's now a SourcePunish issue.
